# Translations template for glance.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the glance project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance 12.0.0.0b2.dev70\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-01-14 06:55+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: glance/location.py:434
#, python-format
msgid ""
"Glance tried all active locations to get data for image %s but all have "
"failed."
msgstr ""

#: glance/notifier.py:364 glance/api/common.py:91
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr ""

#: glance/scrubber.py:275
#, python-format
msgid "Can not get scrub jobs from queue: %s"
msgstr ""

#: glance/scrubber.py:335
#, python-format
msgid "Unable to scrub image %(id)s from a location. Reason: %(exc)s "
msgstr ""

#: glance/api/common.py:54
#, python-format
msgid ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"
msgstr ""

#: glance/api/common.py:60
#, python-format
msgid ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"
msgstr ""

#: glance/api/common.py:119
#, python-format
msgid "Invalid value for option user_storage_quota: %(users_quota)s"
msgstr ""

#: glance/api/middleware/cache.py:171
#, python-format
msgid ""
"Image cache contained image file for image '%s', however the registry did"
" not contain metadata for that image!"
msgstr ""

#: glance/api/middleware/cache.py:270
#, python-format
msgid "could not find %s"
msgstr ""

#: glance/api/middleware/cache.py:289
msgid "Checksum header is missing."
msgstr ""

#: glance/api/v1/images.py:646
#, python-format
msgid "Copy from external source '%(scheme)s' failed for image: %(image)s"
msgstr ""

#: glance/api/v1/upload_utils.py:76
#, python-format
msgid "Unable to kill image %(id)s: "
msgstr ""

#: glance/api/v1/upload_utils.py:270
#, python-format
msgid "Received HTTP error while uploading image %s"
msgstr ""

#: glance/api/v2/image_data.py:59
#, python-format
msgid "Unable to restore image %(image_id)s: %(e)s"
msgstr ""

#: glance/api/v2/image_data.py:75
#, python-format
msgid "Unable to delete image %(image_id)s: %(e)s"
msgstr ""

#: glance/api/v2/image_data.py:184
#, python-format
msgid "Signature verification failed for image %(id)s: %(e)s"
msgstr ""

#: glance/api/v2/image_data.py:193 glance/api/v2/image_data.py:197
msgid "Failed to upload image data due to HTTP error"
msgstr ""

#: glance/api/v2/image_data.py:202
msgid "Failed to upload image data due to internal error"
msgstr ""

#: glance/api/v2/metadef_namespaces.py:206
#, python-format
msgid "Failed to delete namespace %(namespace)s "
msgstr ""

#: glance/api/v3/artifacts.py:390 glance/api/v3/artifacts.py:395
msgid "Failed to upload artifact blob data due to HTTP error"
msgstr ""

#: glance/api/v3/artifacts.py:401
msgid "Failed to upload artifact blob data due to internal error"
msgstr ""

#: glance/api/v3/artifacts.py:446
#, python-format
msgid "Unable to restore artifact %(artifact_id)s: %(e)s"
msgstr ""

#: glance/artifacts/location.py:129
#, python-format
msgid "Failed to delete blob %(blob_id)s from store: %(exc)s"
msgstr ""

#: glance/artifacts/location.py:166
#, python-format
msgid ""
"Glance tried all active locations to get data for blob %s but all have "
"failed."
msgstr ""

#: glance/async/__init__.py:67
msgid ""
"This execution of Tasks is not setup. Please consult the project "
"documentation for more information on the executors available."
msgstr ""

#: glance/async/__init__.py:71
msgid "Internal error occurred while trying to process task."
msgstr ""

#: glance/async/taskflow_executor.py:115 glance/async/taskflow_executor.py:144
#, python-format
msgid "Failed to execute task %(task_id)s: %(exc)s"
msgstr ""

#: glance/async/flows/base_import.py:160
#, python-format
msgid "Failed to execute security checks on the image %(task_id)s: %(exc)s"
msgstr ""

#: glance/async/flows/base_import.py:178
#, python-format
msgid "Task: %(task_id)s failed to import image %(image_id)s to the filesystem."
msgstr ""

#: glance/async/flows/base_import.py:367
#, python-format
msgid "Task ID %s"
msgstr ""

#: glance/async/flows/introspect.py:58
#, python-format
msgid "Failed to execute introspection %(task_id)s: %(exc)s"
msgstr ""

#: glance/common/property_utils.py:79
#, python-format
msgid "Couldn't find property protection file %(file)s: %(error)s."
msgstr ""

#: glance/common/property_utils.py:86
#, python-format
msgid ""
"Invalid value '%s' for 'property_protection_rule_format'. The permitted "
"values are 'roles' and 'policies'"
msgstr ""

#: glance/common/property_utils.py:105
#, python-format
msgid ""
"Multiple policies '%s' not allowed for a given operation. Policies can be"
" combined in the policy file"
msgstr ""

#: glance/common/property_utils.py:118
#, python-format
msgid ""
"Malformed property protection rule in [%(prop)s] %(op)s=%(perm)s: '@' and"
" '!' are mutually exclusive"
msgstr ""

#: glance/common/property_utils.py:143
#, python-format
msgid "Encountered a malformed property protection rule %(rule)s: %(error)s."
msgstr ""

#: glance/common/rpc.py:187
#, python-format
msgid ""
"RPC Call Error: %(val)s\n"
"%(tb)s"
msgstr ""

#: glance/common/signature_utils.py:196
#, python-format
msgid "Unable to create verifier since algorithm is unsupported: %(e)s"
msgstr ""

#: glance/common/signature_utils.py:307
#, python-format
msgid "Unable to retrieve certificate with ID %(id)s: %(e)s"
msgstr ""

#: glance/common/store_utils.py:61
#, python-format
msgid "Failed to delete image %(image_id)s from store: %(exc)s"
msgstr ""

#: glance/common/swift_store_utils.py:80
#, python-format
msgid "swift config file %(conf_file)s:%(exc)s not found"
msgstr ""

#: glance/common/swift_store_utils.py:94
msgid "Invalid format of swift store config cfg"
msgstr ""

#: glance/common/utils.py:107
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr ""

#: glance/common/utils.py:428
msgid ""
"Error setting up the debug environment. Verify that the option "
"pydev_worker_debug_host is pointing to a valid hostname or IP on which a "
"pydev server is listening on the port indicated by "
"pydev_worker_debug_port."
msgstr ""

#: glance/common/wsgi.py:334
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr ""

#: glance/common/wsgi.py:896
#, python-format
msgid "Caught error: %s"
msgstr ""

#: glance/common/artifacts/loader.py:91
#, python-format
msgid "Unable to load artifacts: %s"
msgstr ""

#: glance/common/artifacts/loader.py:159
#, python-format
msgid "Could not load plugin from %(module)s: %(msg)s"
msgstr ""

#: glance/common/location_strategy/__init__.py:63
#, python-format
msgid "Failed to load location strategy module %(module)s: %(e)s"
msgstr ""

#: glance/common/scripts/__init__.py:38
#, python-format
msgid ""
"This task type %(task_type)s is not supported by the current deployment "
"of Glance. Please refer the documentation provided by OpenStack or your "
"operator for more information."
msgstr ""

#: glance/common/scripts/__init__.py:48
#, python-format
msgid "Failed to save task %(task_id)s in DB as task_repo is %(task_repo)s"
msgstr ""

#: glance/common/scripts/utils.py:44
#, python-format
msgid "Task not found for task_id %s"
msgstr ""

#: glance/db/sqlalchemy/api.py:1240
#, python-format
msgid "Invalid value for age, %(age)d"
msgstr ""

#: glance/db/sqlalchemy/api.py:1247
#, python-format
msgid "Invalid value for max_rows, %(max_rows)d"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:346
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:559
msgid "Cannot use this parameter with the operator IN"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:567
#, python-format
msgid "Operator %s is not supported"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:194
#, python-format
msgid "Json schema files not found in %s. Aborting."
msgstr ""

#: glance/db/sqlalchemy/metadata.py:211
#, python-format
msgid ""
"Failed to parse json file %(file_path)s while populating metadata due to:"
" %(error_msg)s"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:462
msgid ""
"To use --prefer_new or --overwrite you need to combine of these options "
"with --merge option."
msgstr ""

#: glance/db/sqlalchemy/metadata.py:467
msgid ""
"Please provide no more than one option from this list: --prefer_new, "
"--overwrite"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:61
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:91
#, python-format
msgid "Invalid store uri for image: %(image_id)s. Details: %(reason)s"
msgstr ""

#: glance/domain/__init__.py:406
#, python-format
msgid ""
"Task [%(task_id)s] status failed to change from %(cur_status)s to "
"%(new_status)s"
msgstr ""

#: glance/domain/__init__.py:512
#, python-format
msgid "Failed to load the %s executor provided in the config."
msgstr ""

#: glance/image_cache/__init__.py:267
#, python-format
msgid ""
"Exception encountered while tee'ing image '%(image_id)s' into cache: "
"%(error)s. Continuing with response."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:393
#, python-format
msgid "Error executing SQLite call. Got error: %s"
msgstr ""

#: glance/registry/api/v1/images.py:134
msgid "Unable to get images"
msgstr ""

#: glance/registry/api/v1/images.py:351
#, python-format
msgid "Unable to show image %s"
msgstr ""

#: glance/registry/api/v1/images.py:383
#, python-format
msgid "Unable to delete image %s"
msgstr ""

#: glance/registry/api/v1/images.py:433
#, python-format
msgid "Unable to create image %s"
msgstr ""

#: glance/registry/api/v1/images.py:502
#, python-format
msgid "Unable to update image %s"
msgstr ""

#: glance/registry/client/v1/client.py:131
#, python-format
msgid "Registry client request %(method)s %(action)s raised %(exc_name)s"
msgstr ""

#: glance/tests/functional/v2/test_metadef_resourcetypes.py:94
#, python-format
msgid "Forbidden to create resource type. Reason: %(reason)s"
msgstr ""

